---
title: "R Notebook"
output: html_notebook
---

```{r,echo=FALSE}
devtools::install_github("JaseZiv/worldfootballR")
library(worldfootballR)
library(dplyr)
```


```{r,echo=FALSE}
epl_2024_urls <- fb_match_urls(country = "ESP", gender = "M", season_end_year = 2024, tier="1st")
print(epl_2024_urls)
```


```{r}
#for (i in 2018:2024)
for (i in 2024:2024)
{
  epl_2024_urls <- fb_match_urls(country = "ENG", gender = "M", season_end_year = i, tier="1st")
  epl_2024_infos <- fb_match_results(country = "ENG", gender = "M", season_end_year = i, tier = "1st")
  for (url in epl_2024_urls){
    epl_2024_squad <- fb_match_lineups(match_url = url)
    epl_2024_goals<- fb_match_summary(match_url = url)
    epl_2024_stats <- fb_team_match_stats(match_url = epl_2024_urls)
    epl_2024_stats_more <- fb_advanced_match_stats(match_url = epl_2024_urls, stat_type = "summary", team_or_player = "team")
    
  }
}
```
```{r}
test_urls_multiple <- c("https://fbref.com/en/matches/c0996cac/Bordeaux-Nantes-August-21-2020-Ligue-1",
                        "https://fbref.com/en/matches/9cbccb37/Dijon-Angers-August-22-2020-Ligue-1")
```

```{r}
epl_2024_urls <- fb_match_urls(country = "ENG", gender = "M", season_end_year = 2024, tier="1st")
```

```{r}
#fbref_match_infos
epl_2024_infos <- fb_match_results(country = "ENG", gender = "M", season_end_year = 2024, tier = "1st")
#in ra
glimpse(epl_2024_infos)

```

```{r}
#fbref_match_squad
epl_2024_squad <- data.frame()
for (i in test_urls_multiple){
	temp <- fb_match_lineups(match_url = i)
	epl_2024_squad <- rbind(epl_2024_squad, temp)
}
```

```{r}
#fbref_match_goals
epl_2024_goals <- data.frame()
for (i in test_urls_multiple){
	temp <- fb_match_summary(match_url = i)
	epl_2024_goals <- rbind(epl_2024_goals, temp)
}
```

```{r}
#fbref_match_stats
epl_2024_stats <- data.frame()
for (i in test_urls_multiple){
	temp <- fb_team_match_stats(match_url = i)
	epl_2024_stats <- rbind(epl_2024_stats, temp)
}
```

```{r}
#more statistic
epl_2024_stats_more <- data.frame()
for (i in test_urls_multiple){
	temp <- fb_advanced_match_stats(match_url = i, stat_type = "summary", team_or_player = "team")
	epl_2024_stats_more <- rbind(epl_2024_stats_more, temp)
}
```

```{r}
    test_url <- c("https://fbref.com/en/matches/f927719d/Ajaccio-Toulouse-May-23-2018-French-12-RelegationPromotion-Play-offs")
tryCatch(
  {
    match_lineups <- fb_match_lineups(match_url = test_url)
    match_summary<- fb_match_summary(match_url = test_url)
    match_stats <- fb_team_match_stats(match_url = test_url)
    advanced_match_stats <- fb_advanced_match_stats(match_url = test_url, stat_type = "summary", team_or_player = "team")
  }, error = function(e) {
    print(paste("Error at URL:", test_url))
    print(paste("Error: ", conditionMessage(e)))
    print("\n")
  }
)
print("HelloWorld")
```
